### ISSUE TITLE
[bug]: IOS App crashes after sign in and later upon every launching

### ISSUE THREAD

**Issue by EvelinaZakharchenko** [helium/wallet-issues-tracker#23]
### bug

**Preconditions:**
1. User has successfully signed in to account via 12 seed words

**Steps:**
1. Open main screen after sign in

**Actual result:**
app crashes upon opening main screen of signed in user and upon each app launching of signed in user

also no ability to link Helium wallet with Maker App via Helium Wallet app due to crash upon launching Helium Wallet app

Screenrecord:
IPhone 8+:
https://user-images.githubusercontent.com/57323258/182366206-a5b16ee1-245f-4c9d-9787-1e78dc8fd154.mov
IPhone 11 cut to hide seed words:
https://user-images.githubusercontent.com/57323258/182387285-93cbf116-14a7-4052-bdf2-eef6185ad0a0.mov

Helium Wallet app version 1.2 from App Store

crash logs:
[HeliumWallet  02.08.2022, 14-29.txt](https://github.com/helium/wallet-issues-tracker/files/9242523/HeliumWallet.02.08.2022.14-29.txt)

### Phone Type

IOS 15.3 IPhone 8+
IOS 14.7 IPhone 11

### Network Type

Mainnet

**Comment by MykhailoMashchenko** [comment]
Definitely happens at some point after using app for a while

**Comment by MykhailoMashchenko** [comment]
Not sure how to use this app if it randomly crashes like that

**Comment by cokes518** [comment]
Thanks for reporting. The fix is coming out in 1.2.1 this week.

**Comment by cokes518** [comment]
We just pushed out 1.2.1 for iOS. It should be available for you shortly to update.

**Comment by Shevchenko-Oleksii** [comment]
@cokes518  Issue still persists on v1.2.1 on ios 15.4.1 Iphone XS MAX

**Comment by matthewcarlreetz** [comment]
@Shevchenko-Oleksii - apologies. I've found the issue and have a fix being reviewed right now.

**Comment by cokes518** [comment]
This is now fixed - app version 1.2.2 is now available on iOS.

**Comment by Shevchenko-Oleksii** [comment]
Working good so far, well done, thanks.

**Comment by EvelinaZakharchenko** [comment]
@matthewcarlreetz @cokes518 Thanks, now it works for IOS. 
But I have also updated app on Android, and now the same crash is on Android. Please, can you fix this for Android app too?

**Comment by Shevchenko-Oleksii** [comment]
> @matthewcarlreetz @cokes518 Thanks, now it works for IOS. But I have also updated app on Android, and now the same crash is on Android. Please, can you fix this for Android app too?

Same crash is observed on Samsung Galaxy S7 android 8.0.0

**Comment by cokes518** [comment]
Android's release is still in review with the PlayStore. It should be available soon (app version 1.2.2)

**Comment by cokes518** [comment]
1.2.2 for Android is now available.
